### PR TITLE
Exporting all pdf destinations with their original name

### PR DESCRIPTION
**Pull request by briha**
This commit is a quick attempt at working towards a solution for https://github.com/u-fischer/newpax/issues/20

In addition to the numbered destinations, it exports all destinations together with their original name, prefixed by <file>.newpax (stripping it of potential path first, see https://github.com/u-fischer/newpax/issues/21).

@u-fischer I am entirely new to LuaTex development, so please let me know if there's anything you'd like to be done differently so that my commit may be incorporated into newpax in the future!

### CODE REVIEW

**Comment by u-fischer** [comment]
I don't have the time now to look, but you should add testfiles.

**Comment by briha** [comment]
Last update rolled back some things, now all it does is to have the lua part properly export all destinations, and serving them with `\NEWPAX@DestProv` and their original name, instead of the ID used for links. These can then be successfully reused to have a working table of content from an included pdf (MWE in #20). 

I am not sure what tests should cover, exactly, as this really does minimal changes and only exports information that is ignored unless used.

**Comment by tobiasBora** [comment]
Just to drop my 2 cents, I can confirm this solves the issue I had here https://tex.stackexchange.com/questions/695277/clickable-includegraphics-for-cross-reference-data

**Comment by u-fischer** [comment]
I have implemented the requested function in a different way as I wanted less duplications in the destinations.

**Pull request closed without merging**
